# Generated by Django 4.0.6 on 2023-05-25 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='', upload_to='cate/%Y/%m/%d/'),
        ),
    ]
