# Generated by Django 4.0.6 on 2023-05-31 17:40

from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimatedVid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('vid_link', embed_video.fields.EmbedVideoField()),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='youtube',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Blog.animatedvid'),
        ),
    ]
