# Generated by Django 4.0.6 on 2023-06-01 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_animatedvid_post_youtube'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animatedvid',
            old_name='vid_link',
            new_name='video',
        ),
    ]
