# Generated by Django 4.0.6 on 2023-06-03 11:31

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_rename_vid_link_animatedvid_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreAnimatedVid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('video', embed_video.fields.EmbedVideoField()),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='animatedvid',
            name='title',
            field=models.CharField(default='tee jay', max_length=100),
        ),
    ]
